import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} antialiased [--pattern-fg:var(--color-neutral-950)]/[0.02] dark:[--pattern-fg:var(--color-neutral-50)]/10`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <main className="bg-background text-foreground h-screen">
            {children}
          </main>
        </ThemeProvider>
      </body>
    </html>
  );
}
